services:
  amnezia-wg-easy:
    # Локальная сборка образа
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    # Имя образа после сборки
    image: amneziawg-vpn:local

    container_name: amnezia-wg-easy
    hostname: amneziawg-server
    restart: unless-stopped

    environment:
      - LANG=${LANG:-ru}
      - PASSWORD_HASH=${PASSWORD_HASH}
      - PORT=${WEB_PORT:-51821}
      - WEBUI_HOST=${WEB_IP:-0.0.0.0}
      - WG_HOST=${WG_HOST}
      - WG_PORT=${WG_PORT:-51820}
      - WG_DEVICE=${WG_DEVICE:-eth0}
      - WG_MTU=${WG_MTU}
      - WG_PERSISTENT_KEEPALIVE=${WG_PERSISTENT_KEEPALIVE:-25}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS:-10.8.0.x}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS:-1.1.1.1}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS:-0.0.0.0/0, ::/0}
      - UI_TRAFFIC_STATS=${UI_TRAFFIC_STATS:-false}
      - ENABLE_PROMETHEUS_METRICS=${ENABLE_PROMETHEUS_METRICS:-false}

    volumes:
      - ./data:/etc/wireguard

    ports:
      - "${WG_PORT:-51820}:${WG_PORT:-51820}/udp"
      - "${WEB_PORT:-51821}:${WEB_PORT:-51821}/tcp"

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW

    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1

    devices:
      - /dev/net/tun:/dev/net/tun
